version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - internal-net
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db

    user: "0:0"
    ports:
      - "27017:27017"
    networks:
      - internal-net
networks:
  internal-net:
